### ISSUE TITLE
Stuttering Caused by Transparency Effects Option in Windows

### ISSUE THREAD

**Issue by Rain623** [Akascape/py-window-styles#10]
System: Windows 10 22H2 19045.3448
GPU: NVIDIA GeForce RTX 3060
Python:3.11.5
Enabling the "Transparency Effects" option in Personalization > Colors leads to severe lag when using transparent themes (acrylic, aero, transparent). When dragging windows, there is a significant delay, with windows gradually moving to the mouse's position. Even after releasing the mouse, the windows continue to move until they reach the final release point. Additionally, the GPU usage of the Desktop Window Manager (dwm.exe) ranges from approximately 5% to 30%.
Disabling the "Transparency Effects" option doesn't result in a noticeable difference in GPU usage by the Desktop Window Manager (dwm.exe), but the lag issue disappears.

code:
```
import tkinter
import pywinstyles

root = tkinter.Tk()
pywinstyles.apply_style(root, "acrylic")

root.mainloop()
```

**Comment by Akascape** [comment]
@Rain623 I know this is a problem, but it works smoother after adding some widget and frames.

**Comment by Rain623** [comment]
@Akascape Even after adding some widget and frames, acrylic and transparency still experience lag, but Aero does not lag (in fact, Aero doesn't lag even without adding widget and frames).There is no significant change in GPU usage.

**Comment by Akascape** [comment]
@Rain623 there will be lag in blurred windows, can't do anything for now. Maybe disable the resizability of the window if you are worried too much.

**Comment by littlewhitecloud** [comment]
It is just a problem of the win32 api, actually, "SetWindowCompositionAttribute" is  a undocumented function and it will cause many problem just like the laggy window.

**Comment by littlewhitecloud** [comment]
Also it won't be too much laggy on windows 11, acrylic and aero are the same effect.
It only use %5 on windows 11 ( I am just using Arc A750 GPU)
![image](https://github.com/Akascape/py-window-styles/assets/71159641/e0702814-b7f7-4fa6-81e3-a66f5fa5d162)

**Comment by Akascape** [comment]
@littlewhitecloud So there is no solution for now. 

> many problem just like the laggy window

what other problems? Not serious I guess.

**Comment by littlewhitecloud** [comment]
I just found a new way to fix it and it won't be lagyyyyyyyyy

**Comment by Akascape** [comment]
@littlewhitecloud Wow, please share the code.

**Comment by littlewhitecloud** [comment]
Clone this repo https://github.com/littlewhitecloud/win32style
And copy this code:
```python
from ctypes import c_char_p, windll
from win32style import *
from tkinter import Tk

w = Tk()
w.title("example")
w.geometry("1080x570")
w.iconbitmap("")
w.config(background="black")
hwnd = windll.user32.FindWindowW(c_char_p(None), "example")

ApplyAcrylic(hwnd, True)
w.mainloop()
```
Then it won't be laggy when you dragging or resizing the window.
It also use no GPU and I don't know why.

**Comment by littlewhitecloud** [comment]
It does these:
* apply the acrylic effect to the titlebar 
* extend the effect to the whole window

**Comment by littlewhitecloud** [comment]
Does it fix the problem?

**Comment by Akascape** [comment]
@littlewhitecloud I will let you know, I am currently not working on this. But will fix it with your method.

**Comment by littlewhitecloud** [comment]
> @littlewhitecloud I will let you know, I am currently not working on this. But will fix it with your method.

Thanks! If you are busy, I can try to use my method in python to fix this.

**Comment by littlewhitecloud** [comment]
> @littlewhitecloud I will let you know, I am currently not working on this. But will fix it with your method.

Let me do that. I'm already fixed it.

**Comment by littlewhitecloud** [comment]
I am not sure about that this patch will work on windows 10?
