### ISSUE TITLE
PySimpleGUI

### ISSUE THREAD

**Issue by peyman1959** [Akascape/py-window-styles#13]
not working with PySimpleGUI
I tried :
`pywinstyles.apply_style(window.TKroot, 'mica')`
and :
`from ctypes import windll
import pywinstyles
hwnd = windll.user32.GetActiveWindow() 
pywinstyles.change_header_color(hwnd, color="blue")`

**Comment by Akascape** [comment]
@peyman1959 are other styles working with the second method? Are you on windows 10? 

If not, try to find methods of finding HWND of your pysimpleGUI window.

**Comment by Akascape** [comment]
@peyman1959 I got the fix, you have **finalize** the window before adding running any function.
```python
window = sg.Window("Demo", layout, finalize=True)

pywinstyles.change_header_color(window.TKroot, color="blue")
...
```
