### ISSUE TITLE
acrylic on windows 11

### ISSUE THREAD

**Issue by youngtutorsuk** [Akascape/py-window-styles#17]
import customtkinter
import os
from PIL import Image
import pywinstyles

class App(customtkinter.CTk):
    def __init__(self):
        super().__init__()

        self.title("TASK V1")
        self.iconbitmap(r"C:\Users\musta\Downloads\New folder\bot.ico")
        self.grid_rowconfigure(1, weight=1)
        self.columnconfigure(2, weight=1)
        
        

        # create scrollable checkbox frame
        self.scrollable_checkbox_frame = ScrollableCheckBoxFrame(master=self, width=200, command=self.checkbox_frame_event,
                                                                 item_list=[f"item {i}" for i in range(15)])
        self.scrollable_checkbox_frame.grid(row=1, column=0, padx=15, pady=15, sticky="ns")
   
    

#if __name__ == "__main__":

app = App()
pywinstyles.apply_style(app, 'acrylic')
app.mainloop()
self.toplevel_window.focus()
 not particularly the code but across all the gui's that were previously working with the acrylic window now only appear slightly grey
ever since my laptop updated to the latest windows 11 update

**Comment by littlewhitecloud** [comment]
Not getting this error, if you got something like this:
![image](https://github.com/Akascape/py-window-styles/assets/71159641/28a2f689-f8c7-4a7e-820b-10794e70107a)
That means your window is not focus every time.

**Comment by Akascape** [comment]
@youngtutorsuk Try aero theme

**Comment by youngtutorsuk** [comment]
with aero theme the background and title bar to turn black

**Comment by littlewhitecloud** [comment]
Again, I am still not getting the black background.
![image](https://github.com/Akascape/py-window-styles/assets/71159641/6c418f72-9382-4694-9f48-12f12c44f95c)

Also, acrylic works fine on Windows 11. (But it seems that it don't work fine on Windows 10)
![image](https://github.com/Akascape/py-window-styles/assets/71159641/7e3ca982-c136-4199-b1cd-064b4934f9a6)

**Comment by youngtutorsuk** [comment]
Windows 11 Home version 23H2 osbuild  22631.3155

**Comment by Akascape** [comment]
@littlewhitecloud I am also using the same version 23H2 osbuild 22631.3155, this is the acrylic and aero themes:
![image](https://github.com/Akascape/py-window-styles/assets/89206401/e0f86b26-ca09-4520-a6b9-44d846a6366e)

**Comment by Akascape** [comment]
Acrylic has been modified to reduce gpu usage, but there is a focus out issue with that.

**Comment by littlewhitecloud** [comment]
> @littlewhitecloud I am also using the same version 23H2 osbuild 22631.3155, this is the acrylic and aero themes: ![image](https://private-user-images.githubusercontent.com/89206401/313199818-e0f86b26-ca09-4520-a6b9-44d846a6366e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTAzMjgsIm5iZiI6MTcxMDU5MDAyOCwicGF0aCI6Ii84OTIwNjQwMS8zMTMxOTk4MTgtZTBmODZiMjYtY2EwOS00NTIwLWE2YjktNDRkODQ2YTYzNjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDExNTM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwYzg4NWUwNDdjZmI0ZDZmY2E0ZmI1Mzk2NzJlYTI3NDgxOGVmNzJiMGJmYzVkODVjMTc0YmZjYjQ5YWY2Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8PJkp3og_hOrEgNQOzZM1kAXuMnn19F_4yMyf6Jr-mg)

Does it work well? Or what's the meaning of the slight grey?

**Comment by Akascape** [comment]
@littlewhitecloud the window looks a little greyish in this version, that's all. And the focus out removes all the transparency and make it grey.

**Comment by littlewhitecloud** [comment]
> @littlewhitecloud the window looks a little greyish in this version, that's all. And the focus out removes all the transparency and make it grey.

I see.
Maybe this color argument makes the window looks a bit grey.
https://github.com/Akascape/py-window-styles/blob/d3aaf0a6fc4a905eec0d3a21820f3caa48f12d28/pywinstyles/py_win_style.py#L81C1-L81C62

**Comment by littlewhitecloud** [comment]
![image](https://github.com/Akascape/py-window-styles/assets/71159641/0a5214ba-074a-444a-814c-9c20174aec20)
I have just updated windows11 and now it is 22631.3296.
Everythings works as fine as the version below.


> with aero theme the background and title bar to turn black

The titlebar will turn black right, but if the background turns black too, I think maybe you used ExtendFrameIntoClientArea. Or the aero theme were not applied.
![image](https://github.com/Akascape/py-window-styles/assets/71159641/596005af-31ff-46c6-88dc-1f0dea677e1e)

> Acrylic has been modified to reduce gpu usage, but there is a focus out issue with that. But aero is still not changed and uses gpu, so use aero in that case.

Also, the window with acrylic effect may turn grey after focus out, it is legall. Because it can reduce the GPU usage and use less resource when the window is focus out and don't need to draw that. The window with mica effect will also turn grey.

**Comment by Akascape** [comment]
@littlewhitecloud No

**Comment by youngtutorsuk** [comment]
the aero theme turns the background black and acrylic tints everything light grey

**Comment by Akascape** [comment]
@youngtutorsuk I guess you have to turn on the `transparency effects` mode in settings.

![](https://www.groovypost.com/wp-content/uploads/2023/06/taskbar-translucent-win11-transparency-on.png)

And also turn off the battery saver mode.
