### ISSUE TITLE
bug :/

### ISSUE THREAD

**Issue by Thisal-D** [Akascape/py-window-styles#23]
## without using pywinstyles

![image](https://github.com/Akascape/py-window-styles/assets/93121062/83eedf51-f0f7-499c-b939-56bdab67fe53)

<hr>

## after using pywinstyles

```
pywinstyles.apply_style(app, "aero")  # here app is CTk (root)
pywinstyles.set_opacity(app, 0.8)
```

- something isn't right :/

![Screenshot 2024-04-12 083649](https://github.com/Akascape/py-window-styles/assets/93121062/1def6aba-81c9-4fd6-b07c-cfb6c0d25fd7)

![Screenshot 2024-04-12 083333](https://github.com/Akascape/py-window-styles/assets/93121062/383b7f82-a527-461e-b86f-aca58eb1ed9b)

**Comment by Akascape** [comment]
@Thisal-D Do you have some scrollable frames below the topmost frame?
I suggest you to remove those from the the windows when it's hidden.

**Comment by Thisal-D** [comment]
> @Thisal-D Do you have some widgets below the topmost frame?
> I suggest you to remove those from the the window when it's hidden.
> 
> 
> There was no any widgets below the scrollable frame :/

**Comment by Akascape** [comment]
@Thisal-D Is this happening in a plain windows?

**Comment by Thisal-D** [comment]
> @Thisal-D Is this happening in a plain windows?

![Screenshot 2024-04-12 174251](https://github.com/Akascape/py-window-styles/assets/93121062/85b6987a-f534-4f6a-91e0-ce38d1b155d1)


yeah its happenning :/

**Comment by Thisal-D** [comment]
> @Thisal-D Is this happening in a plain windows?

[Uploading 2024-04-12 17-47-48.mp4…](https://github.com/Akascape/py-window-styles/assets/93121062/11e89649-11a9-4281-8daf-b2ce348dfca9)

i think problem start  with set_opacity method ....

**Comment by Akascape** [comment]
@Thisal-D Try adding  `self.update()` method. 

I will try to fix it later.

**Comment by Akascape** [comment]
@Thisal-D This is an internal bug when you use set_opacity method to root window. I recommend you to use `root.wm_attributes("-alpha", 0.8)` method for root windows. set_opacity method is only for widgets not window.

**Comment by Thisal-D** [comment]
> @Thisal-D This is an internal bug when you use set_opacity method to root window. I recommend you to use `root.wm_attributes("-alpha", 0.8)` method for root windows. set_opacity method is only for widgets not window. 

@Akascape Ok .
