### ISSUE TITLE
The title bar is not displayed properly under dark theme

### ISSUE THREAD

**Issue by Xiaokang2022** [Akascape/py-window-styles#32]
* OS: `Windows 10 22H2 (19045.4529)`
* Python: `3.12.3`
* pywinstyles: `1.8`
* GUI Lib: `tkinter`

When using the dark theme, the title bar of the window is not dark, but looks like this:

<img width="658" alt="1" src="https://github.com/Akascape/py-window-styles/assets/100004682/06f721ce-81c1-4eee-a99b-577052e9fed7">

When the window has undergone some operations, such as losing focus and regaining focus, or zooming, the title bar of the window will display normally:

<img width="650" alt="2" src="https://github.com/Akascape/py-window-styles/assets/100004682/6c664d97-63bd-4bd4-ae27-e116714e7650">

**Comment by Akascape** [comment]
@Xiaokang2022 Try the optimised mode, or maybe add `root.update()` or `root.focus_set()`.

**Comment by Xiaokang2022** [comment]
I tried the three methods you said, but they didn't work

**Comment by Xiaokang2022** [comment]
I have two computers, one with Windows 10 and the other with Windows 11. This issue doesn't occur on my Windows 11 computer. So this could be system-related? I want my program to work the same on both computers.

**Comment by Akascape** [comment]
@Xiaokang2022 Yes, it can be issue related to windows 10. But try different methods to solve this.
- `root.withdraw()` and `root.deiconify()`
- `root.update_idletasks()`

**Comment by Xiaokang2022** [comment]
> @Xiaokang2022 Yes, it can be issue related to windows 10. But try different methods to solve this.
> 
> * `root.withdraw()` and `root.deiconify()`
> * `root.update_idletasks()`

Maybe it's not a good solution, but it works, thanks!

**Comment by littlewhitecloud** [comment]
@Akascape It may cause by `ExtendFrameIntoClientArea` so the titlebar's color was mixed with the backrgound forcely.
