### ISSUE TITLE
PyQt5. Win 10. The changes apply only to the specified window.

### ISSUE THREAD

**Issue by Yrij-Zhavoronkov** [Akascape/py-window-styles#33]
The changes apply only to the specified window. Dialogs, messages, and newly created windows do not inherit the style of the main window.

**Comment by Akascape** [comment]
@Yrij-Zhavoronkov You have to apply the style for those windows separately.

**Comment by Yrij-Zhavoronkov** [comment]
> @Yrij-Zhavoronkov You have to apply the style for those windows separately.

It is clear that it can be applied separately to each. Is there no way not to do this?

**Comment by Akascape** [comment]
@Yrij-Zhavoronkov Yes, you must do this with every separate window/toplevel as each window has their own ID and different attributes.

**Comment by Yrij-Zhavoronkov** [comment]
Ok, thanks for information ;)
