### ISSUE TITLE
Can't change window style while use 'acrylic' style in customtkinter in Win11

### ISSUE THREAD

**Issue by KianaK204** [Akascape/py-window-styles#35]
When I use 
`pywinstyles.apply_style(self,"light")` and `pywinstyles.apply_style(self,"dark") ` 
to switch my window style,it works.

But when i use `pywinstyles.apply_style(self,"light") `and `pywinstyles.apply_style(self,"acrylic")` ,
"light" to "acrylic" is ok, but "acrylic" to "light" doesn't work.

**Comment by Akascape** [comment]
@KianaK204 Try to add `pywinstyles.apply_style(self, "normal")` in between switching themes.

**Comment by littlewhitecloud** [comment]
https://github.com/Akascape/py-window-styles/blob/edc944e4fb3f9147b01c9249300141c84b1847f3/pywinstyles/py_win_style.py#L83

This will force darkmode I think.

**Comment by littlewhitecloud** [comment]
Actually, it has changed the titlebar's color
Dark:
![image](https://github.com/user-attachments/assets/bbfa3c69-a3ff-468d-b0c1-328a22c29f3d)
Light:
![image](https://github.com/user-attachments/assets/54a0e8f1-c026-44d4-866c-9a63a3963b17)

"dark" or "light" only changes the color of the titlebar.

as akaspace says use "normal" to clear the acrylic effect

**Comment by KianaK204** [comment]
> @KianaK204 Try to add `pywinstyles.apply_style(self, "normal")` in between switching themes.

it works,thank you very much.
