### ISSUE TITLE
Problem with window returning to normal position when switching

### ISSUE THREAD

**Issue by CheckAvaliable** [Akascape/py-window-styles#5]
For example, when pywinstyles.apply_style(self, "aero") is called, the theme is installed and works. However, after that you can call another theme as much as you want by means of pywinstyles.apply_style(self, "dark"), for example. 
All the code in text is available in my "changer" repository.
![image](https://github.com/Akascape/py-window-styles/assets/137236771/78bb01c9-e09a-4e81-b10c-8960efc63d82)

**Comment by CheckAvaliable** [comment]
Of course I forgot to add that reapplying the theme completely fails.

**Comment by Akascape** [comment]
@CheckAvaliable Fixed, now you can pass "normal" as style to make the window style default.
