### ISSUE TITLE
How to dynamically remove the border color on a button click??

### ISSUE THREAD

**Issue by Zingzy** [Akascape/py-window-styles#6]

**Comment by Zingzy** [comment]
After I have applied the border color , i want to remove it when a user clicks a button, any idea how to do it??

**Comment by Akascape** [comment]
That's the thing I am not working on right now. I have to research about the API on reverting themes back to original.

**Comment by Zingzy** [comment]
> That's the thing I am not working on right now. I have to research about the API on reverting themes back to original.

No like I only want to remove the border color not any other theme

**Comment by Zingzy** [comment]
> That's the thing I am not working on right now. I have to research about the API on reverting themes back to original.

also can you mention the API you use to change the window border color? hopefully I can search about some fixes?

**Comment by Akascape** [comment]
@Zingzy 
> No like I only want to remove the border color not any other theme

Yeah, I mean all those options including the themes.

> also can you mention the API you use to change the window border color? hopefully I can search about some fixes?

It's the DWMApi
https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmsetwindowattribute

**Comment by Zingzy** [comment]
> @Zingzy
> 
> > No like I only want to remove the border color not any other theme
> 
> Yeah, I mean all those options including the themes.
> 
> > also can you mention the API you use to change the window border color? hopefully I can search about some fixes?
> 
> It's the DWMApi https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmsetwindowattribute

also sir do you know any way on how to get the user's accent color?

**Comment by Akascape** [comment]
@Zingzy I am not sure but [DWMGetWindowAttribute](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmgetwindowattribute) can help. I will try implement this feature later.

**Comment by Zingzy** [comment]
> @Zingzy I am not sure but [DWMGetWindowAttribute](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmgetwindowattribute) can help. I will try implement this feature later.

Ok thanks a lot

**Comment by Akascape** [comment]
@littlewhitecloud Hey bro, need a little help with this issue. I found that [GetThemeSysColor](https://learn.microsoft.com/en-us/windows/win32/api/uxtheme/nf-uxtheme-getthemesyscolor) attribute can help to get the windows accent color. Can you help to figure out the correct process of using it with ctypes? I somehow managed to use the term but I don't know how I can get the COLOREF value returned.

```python
from ctypes import POINTER, pointer, sizeof, windll, Structure, byref, c_int, c_wchar_p
from ctypes.wintypes import DWORD, ULONG, COLORREF, HANDLE, HWND

...
HWND = windll.user32.GetParent(window.winfo_id())
HTHEME = HANDLE

GetColor = windll.UxTheme.GetThemeSysColor
GetColor.argtypes = [HTHEME, c_int]
GetColor.restype = COLORREF

OpenThemeData = windll.uxtheme.OpenThemeData
OpenThemeData.argtypes = [HWND, c_wchar_p]
OpenThemeData.restype = HTHEME
htheme = OpenThemeData(hWnd, 'Window')
color = GetColor(htheme, c_int(1))
print(color)
```

**Comment by Zingzy** [comment]
> @littlewhitecloud Hey bro, need a little help with this issue. I want to get the accent color of windows. I found that [GetThemeSysColor](https://learn.microsoft.com/en-us/windows/win32/api/uxtheme/nf-uxtheme-getthemesyscolor) attribute can help. Idk, but there can also be a different term for this. Can you help to figure out the correct process of using it with ctypes? I somehow managed to use the term but I don't know how I can get the COLOREF value returned.
> 
> ```python
> from ctypes import POINTER, pointer, sizeof, windll, Structure, byref, c_int, c_wchar_p
> from ctypes.wintypes import DWORD, ULONG, COLORREF, HANDLE, HWND
> 
> ...
> HWND = windll.user32.GetParent(window.winfo_id())
> HTHEME = HANDLE
> 
> GetColor = windll.UxTheme.GetThemeSysColor
> GetColor.argtypes = [HTHEME, c_int]
> GetColor.restype = COLORREF
> 
> OpenThemeData = windll.uxtheme.OpenThemeData
> OpenThemeData.argtypes = [HWND, c_wchar_p]
> OpenThemeData.restype = HTHEME
> htheme = OpenThemeData(hWnd, 'Window')
> color = GetColor(htheme, c_int(1))
> print(color)
> ```

Thanks but actually I found a better solution to get the accent color using Registry Keys and about reverting the border color, I detected the original border color of the window and changed it's color to that to remove the custom border

**Comment by Akascape** [comment]
@Zingzy So what is the method in python? I wish if we can implement this in the package.

**Comment by Zingzy** [comment]
> @Zingzy So what is the method for python (getting the accent color)? I wish we can implement this in the package.

Should I share the code over here?

**Comment by Akascape** [comment]
Yeah the process of getting the color from registry.

**Comment by Zingzy** [comment]
> @Zingzy Yeah the process of getting the color from registry with python

`import winreg

def get_accent():
    key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, r'Software\Microsoft\Windows\DWM')
    value, type = winreg.QueryValueEx(key, 'ColorizationAfterglow')
    winreg.CloseKey(key)
    return hex(value)

`

**Comment by Akascape** [comment]
@Zingzy Thanks bro, I implemented this successfully.

**Comment by Zingzy** [comment]
> @Zingzy Thanks bro, I implemented this successfully.

No worries! Did you implement it in this library?

**Comment by Akascape** [comment]
@Zingzy Will update it soon.

**Comment by Akascape** [comment]
@Zingzy Bro what will be the reg key for default border color?

**Comment by Zingzy** [comment]
> @Zingzy Bro what will be the reg key for default border color?

I didnt use registry to get the default color, I used a color picker application to get the default color (the default color may vary in different versions of windows tho)... Also I think there must be some registry key which contains the default windows border color

**Comment by Akascape** [comment]
Ok, then no need to add this one.

**Comment by Akascape** [comment]
@Zingzy Updated, now we have `pywinstyles.get_accent_color()`

**Comment by Zingzy** [comment]
> @Zingzy Updated, now we have `pywinstyles.get_accent_color()`

amazing! But you might wanna give me some credits? (its completely upto you tho, I will not mind if you will not 😄)

**Comment by Akascape** [comment]
@Zingzy Ok, will add your name in that section :)
